### ISSUE TITLE
tabs instead of spaces?

### ISSUE THREAD

**Issue by jonorthwash** [ftyers/txuvaix#3]
Could we decide to use tabs instead of spaces?

**Comment by ftyers** [comment]
I tend to use two spaces with XML, or lay it out however it looks nice. But I'm happy either way.

**Comment by jonorthwash** [comment]
We can mix tabs and spaces if needed to help it look better (e.g., for indented lines).  And you can just set your tabstop to 2 if that's how you like it to look.  (I like using 3 spaces, fwiw, so I just set my tabstop to that.)
